site_name: My Docs

nav:
  - Basics:
    - Introduction: basics/00-intro.md
    - Set LED Color: basics/01-set-led-color.md
    - Blink: basics/02-blink.md
    - Alternate Blink: basics/03-alternate-blink.md
    - Ping Color: basics/04-ping-color.md
    - Random Color: basics/04-random-color.md
    - Green To Go: basics/05-green-to-go.md
    - Rainbow Color: basics/06-rainbow-colors.md
    - Drive Square: basics/07-drive-square.md
    - Collision Avoidance: basics/08-collision-avoidance.md
    - Dance: basics/08-dance.md
    - Collision Avoidance Random: basics/09-collision-avoidance-random.md
    - Collision Avoidance Reverse: basics/10-collision-avoidance-reverse.md
    - Line Follower: basics/10-line-follower.md
    - Collision Avoidance LED Status: basics/11-collision-avoidance-led-status.md
    - Cliff Detection: basics/12-cliff-detection.md
- Glossary: glossary.md
- References: references.md
- Contact: contact.md

site_description: 'Resources for teaching MicroPython to CoderDojo Twin Cities students.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/micropython'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
